version: '3'
services:
    mariadb:
        image: 'bitnami/mariadb:10.1'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=spdf_user
            - MARIADB_DATABASE=spdf
            - MARIADB_PASSWORD=spdf_password

    spdf-laravel:
        tty: true
        image: bitnami/laravel:7
        environment:
            - DB_HOST=mariadb
            - DB_USERNAME=spdf_user
            - DB_DATABASE=spdf
            - DB_PASSWORD=spdf_password
            - RENDER_PDF_FILE=http://localhost:3000/storage/contracts/
        depends_on:
            - mariadb
        ports:
            - 3000:3000
            - 3001:8000
        volumes:
            - ./:/app
        # privileged: true # Privileged mode could be required to run this container under Windows
